#pragma once

#include "log/Log.hpp"

#include "math/Mat2x2.hpp"
#include "math/Mat3x3.hpp"
#include "math/Mat4x4.hpp"
#include "math/Vec2.hpp"
#include "math/Vec3.hpp"
#include "math/Vec4.hpp"
#include "math/util.hpp"

#include "pal/EventHandler.hpp"
#include "pal/EventPump.hpp"
#include "pal/Keys.hpp"
#include "pal/MouseButtons.hpp"
#include "pal/Window.hpp"
#include "pal/WindowHandle.hpp"

#include "pal/rhi/Painter.hpp"
#include "pal/rhi/RenderContext.hpp"
#include "pal/rhi/RenderDevice.hpp"
#include "pal/rhi/RenderTarget.hpp"
#include "pal/rhi/SwapChain.hpp"
#include "pal/rhi/VertexBuffer.hpp"

#include "sg/Camera3D.hpp"
#include "sg/Line2D.hpp"
#include "sg/MeshNode3D.hpp"
#include "sg/NodeVisitor.hpp"
#include "sg/OrthoCamera3D.hpp"
#include "sg/PerspCamera3D.hpp"
#include "sg/Rect2D.hpp"
#include "sg/SceneNode.hpp"
#include "sg/SceneNode2D.hpp"
#include "sg/SceneNode3D.hpp"
#include "sg/Transform2D.hpp"
#include "sg/Transform3D.hpp"

#include "Color.hpp"
#include "Point2.hpp"
#include "RenderView.hpp"
#include "SceneGraph.hpp"
#include "Size2.hpp"
